### ISSUE TITLE
OverflowError with filenames with long numbers in it.

### ISSUE THREAD

**Issue by SamRichardsDisney** [sqlboy/fileseq#44] opened 2017-04-09 19:26 UTC
I'm (perhaps supidly) using it when iterating through our file-system using a combination of os.walk and fileseq.findSequencesInList, and there are a couple of edge-cases that are causing it to error out with: OverflowError: Python int too large to convert to C long

Obviously I can catch it, but I'm wondering if should be handled internally.

Case 1:
A directory with the following splendidly named files:
```
-4780394256886551358.tmp
-5210526082881518455.tmp
-5413498426633446015.tmp
```

(Not quite sure where they are coming from, but I'm suspecting aspera). The drag is that this was in a directory with some sequences that I would like to pick up.

Case 2:
```
thumbcanon___063078065293.png
thumbcanon___063078065294.png
thumbcanon___242076169693.png
thumbcanon___242076169694.png
thumbcanon___242076169695.png

```
In this case these numbers are actually serial numbers.

Thanks for the work on this...

Sam.

**Comment by justinfx** [comment] 2017-04-09 21:35
Hi Sam. Can you give the full traceback and repro? Also, are you on a 32-bit python?
Thanks!

**Comment by SamRichardsDisney** [comment] 2017-04-09 22:34
I'm pretty sure its 64 bit, I've attached a simple test case. In setting up the test, the error is more clearly in format, rather than the initial sequence parsing.

[fileseqtest.tar.gz](https://github.com/sqlboy/fileseq/files/908601/fileseqtest.tar.gz)

Sam.

**Comment by justinfx** [comment] 2017-04-10 21:46
Interesting. What was the actual traceback you got? For me, the implicit call that `format()` makes to `invertedFrameRange()` causes a `MemoryError`. This makes sense because its trying to construct this massive list of the frames not in the original range. 

This was actually a design issue I ran up against as well in the Python implementation, which led me to take a completely different approach in the C++ and Go implementations. Those impls don't ever expand out a complete list of frame values. Instead they always represent everything as a collection of ranges and calculate values on the fly. This prevented the problem you are seeing where poorly named (or even well named by huge frame) files could trigger memory issues. Check out how long this operation takes and how much memory it consumes:

```python
fs = fileseq.FrameSet('1-10000000')
```

I feel like a fileseq 2.0 should follow the implementation of these ports:

https://github.com/justinfx/gofileseq
https://github.com/justinfx/gofileseq/tree/master/cpp-port

But for this 1.x implementation, we probably need to add better handling to these cases. Maybe we need to catch the case of a `FrameSet` wanting to construct something larger than `MAX_FRAMESET_SIZE` and fail with a documented exception. A default value could be something like 10 million?

@sqlboy , any opinion on this?

**Comment by SamRichardsDisney** [comment] 2017-04-16 05:24
Sorry for taking a week to get back...

On windows I get:
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    print ", ".join([s.format() for s in seqs])
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\filesequence.py", line 90, in format
    inverted=self.invertedFrameRange() or "",
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\filesequence.py", line 239, in invertedFrameRange
    return self._frameSet.invertedFrameRange(self._zfill)
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\frameset.py", line 310, in invertedFrameRange
    result += xrange(frame + 1, next_frame)
OverflowError: Python int too large to convert to C long

On mac I get:

python(36311,0x7fff77c5f000) malloc: *** mach_vm_map(size=1826751093767348224) failed (error code=3)

*** error: can't allocate region

*** set a breakpoint in malloc_error_break to debug

Traceback (most recent call last):

  File "t.py", line 4, in <module>

    print ", ".join([s.format() for s in seqs])

  File "/wdi/tools/rez/packages/ext/fileseq/1.3.0/python/fileseq/filesequence.py", line 90, in format

    inverted=self.invertedFrameRange() or "",

  File "/wdi/tools/rez/packages/ext/fileseq/1.3.0/python/fileseq/filesequence.py", line 239, in invertedFrameRange

    return self._frameSet.invertedFrameRange(self._zfill)

  File "/wdi/tools/rez/packages/ext/fileseq/1.3.0/python/fileseq/frameset.py", line 310, in invertedFrameRange

    result += xrange(frame + 1, next_frame)

MemoryError

What you suggest makes sense to me...

Sam.
--
Sam Richards
VFX Manager
Walt Disney Imagineering
818-544-4169 Office
sam.richards@disney.com<mailto:sam.richards@disney.com>



On Apr 10, 2017, at 2:46 PM, Justin Israel <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. What was the actual traceback you got? For me, the implicit call that format() makes to invertedFrameRange() causes a MemoryError. This makes sense because its trying to construct this massive list of the frames not in the original range.

This was actually a design issue I ran up against as well in the Python implementation, which led me to take a completely different approach in the C++ and Go implementations. Those impls don't ever expand out a complete list of frame values. Instead they always represent everything as a collection of ranges and calculate values on the fly. This prevented the problem you are seeing where poorly named (or even well named by huge frame) files could trigger memory issues. Check out how long this operation takes and how much memory it consumes:

fs = fileseq.FrameSet('1-10000000')

I feel like a fileseq 2.0 should follow the implementation of these ports:

https://github.com/justinfx/gofileseq
https://github.com/justinfx/gofileseq/tree/master/cpp-port

But for this 1.x implementation, we probably need to add better handling to these cases. Maybe we need to catch the case of a FrameSet wanting to construct something larger than MAX_FRAMESET_SIZE and fail with a documented exception. A default value could be something like 10 million?

@sqlboy<https://github.com/sqlboy> , any opinion on this?

**Comment by justinfx** [comment] 2017-04-16 05:51
Thanks for the updated info. So that is the behaviour on windows vs posix. Good to know.

Can you take a look at the proposed #45 merge that I just pushed? I would like to know some user feedback about whether this approach is too aggressive. For instance, what would you expect, as user, to happen if you were to construct a `FrameSet` with values that were too large? Or, when you say fileseq should handle the memory error internally when calling `format()` or `invert()`, does that mean a better error being raised as I have done?

We can continue technical discussions in #45 about that specific code. But it would be good to know in this thread what your expectations as a user are, for the handling of this memory error given your particular use case.

Thanks!

**Comment by michaelmovies** [comment] 2017-04-16 06:31
Hey guys,

Bit of a drive by observation, as I'm not able to look at or run the code right now, but I think we're possibly running into a limitation of xrange in the C implementation of Python 2.7:

https://docs.python.org/2.7/library/functions.html#xrange

The Python 3 update to range works like xrange, but doesn't have this implementation issue, but try this in an interpreter:

```
import sys
list(xrange(sys.maxint, sys.maxint+1))
```

And it should fail; irritatingly int(sys.maxint+1) doesn't fail, and more irritatingly sys.maxint on 64 bit windows is apparently smaller than sys.maxint on 64 bit linux.

This should work as a drop in replace, but no idea if there will be a performance hit:

```
import sys
from itertools import islice, count

def xrange(start, stop=None, step=1):
if stop is None:
start, stop = 0, start
return islice(count(start, step), (stop-start+step-1+2*(step<0))//step)
```

Also not sure if that will solve the problem on Mac, as I think the memory error should only occur if building a list that has too many items in it, ie list(xrange(really_big_number)).

M

**Comment by justinfx** [comment] 2017-04-16 07:43
@michaelmovies , thanks for chiming in and providing extra info!

It seems @SamRichardsDisney is using a 32-bit build of python (I am guessing) even though he happens to be on a 64 bit Windows. It is now easy to reproduce the problem, if I run a 32-bit build of python on osx:

```
$ python2.7-32   
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.maxint
2147483647
>>> xrange(1, sys.maxint+1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

Now, even with your suggestion of an alternate itertools-based implementation of xrange (as provided by the docs), you could still crash the 32-bit python interpreter if you create a `FrameSet` larger than `sys.maxint`:

```
>>> ret = list(xrange2(1, sys.maxint+1))
Python(52462,0xa3754000) malloc: *** mach_vm_map(size=8388608) failed (error code=3)
*** error: can't allocate region securely
*** set a breakpoint in malloc_error_break to debug
```

So what would be the reasonable approach here? Do we catch the case of trying to exceed `sys.maxint` in both a start/stop/step value, and in the size of the value set? And then we raise `MaxSizeException`? In #45, I am catching the case where we exceed a reasonable max constant value for `FrameSet` size. But I am not yet checking specific values.

This was all something I had problems with a while back, which is why the implementation I wrote in my own ports of this python lib use the different approach. See:

https://github.com/justinfx/gofileseq/blob/master/ranges/ranges.go
https://github.com/justinfx/gofileseq/blob/master/cpp-port/ranges/ranges.cpp

**Comment by michaelmovies** [comment] 2017-04-16 08:11
Not entirely sure if he's using a 32 bit build, as some discussion I've seen around while researching the xrange limitation implies that on a Windows a C-native Long, and therefore the maximum size of any argument to xrange, is 32 bits even on 64 bit builds. Go figure.

I think we've got two issues; if you pass arguments larger than sys.maxint to xrange you get the overflow, and if you ever pass into list() a generator that ultimately produces more than sys.maxsize items you'll get a out of memory. The maxint and maxsize values, IIRC, are not the same on all platforms.

I do think there's something very sensible in failing with a more legible error when either condition is met, but ultimately the problem stems from the data structure we chose and the constraint of trying to maintain sort order. Not sure what the solution is, though I tend to think that any file visited that's got a frame number greater than 32 bits in length, or a file sequence anywhere near that long, is probably an outlier or error well outside the scope of the problem we're trying to solve.

M

**Comment by SamRichardsDisney** [comment] 2017-04-16 18:08
Both were 64-bit, here is another dump of the windows one:
Z:\tmp\fileseqtest>python
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import t.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "t.py", line 4, in <module>
    print ", ".join([s.format() for s in seqs])
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\filesequence.py", line 90, in format
    inverted=self.invertedFrameRange() or "",
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\filesequence.py", line 239, in invertedFrameRange
    return self._frameSet.invertedFrameRange(self._zfill)
  File "C:\Panda3D-1.9.0-x64\python\lib\site-packages\fileseq\frameset.py", line 310, in invertedFrameRange
    result += xrange(frame + 1, next_frame)
OverflowError: Python int too large to convert to C long
>>>

I agree to some sensible limits, file-sequences in the millions is getting a bit excessive, billions definately so.

Sam.
--
Sam Richards
VFX Manager
Walt Disney Imagineering
818-544-4169 Office
sam.richards@disney.com<mailto:sam.richards@disney.com>



On Apr 16, 2017, at 1:11 AM, Michael Morehouse <notifications@github.com<mailto:notifications@github.com>> wrote:

Not entirely sure if he's using a 32 bit build, as some discussion I've seen around while researching the xrange limitation implies that on a Windows a C-native Long, and therefore the maximum size of any argument to xrange, is 32 bits even on 64 bit builds. Go figure.

I think we've got two issues; if you pass arguments larger than sys.maxint to xrange you get the overflow, and if you ever pass into list() a generator that ultimately produces more than sys.maxsize items you'll get a out of memory. The maxint and maxsize values, IIRC, are not the same on all platforms.

I do think there's something very sensible in failing with a more legible error when either condition is met, but ultimately the problem stems from the data structure we chose and the constraint of trying to maintain sort order. Not sure what the solution is, though I tend to think that any file visited that's got a frame number greater than 32 bits in length, or a file sequence anywhere near that long, is probably an outlier or error well outside the scope of the problem we're trying to solve.

M

**Comment by justinfx** [comment] 2017-04-16 21:12
Ok, for the windows-specific issue I will add an extra check for values being greater than `sys.maxint` (or investigate switching to the itertools approach). Even at 60 FPS, `MAX_FRAME_SIZE=10000000` is still over 2 days of time. On my machine it allocates over 800mb in a `FrameSet` and takes over 4 seconds to allocate. Seems undesirable.

**Comment by justinfx** [comment] 2017-04-16 23:04
In #45 I have added a platform specific switch which swaps `xrange` for the itertools impl. @SamRichardsDisney , even though it is passing appveyor tests, it would be great to have to try a run with that branch before it gets merged.

**Comment by SamRichardsDisney** [comment] 2017-04-19 14:54
Its working great! Thanks for the quick turnaround.

Sam.
--
Sam Richards
VFX Manager
Walt Disney Imagineering
818-544-4169 Office
sam.richards@disney.com<mailto:sam.richards@disney.com>



On Apr 16, 2017, at 4:04 PM, Justin Israel <notifications@github.com<mailto:notifications@github.com>> wrote:


In #45<https://github.com/sqlboy/fileseq/pull/45> I have added a platform specific switch which swaps xrange for the itertools impl. @SamRichardsDisney<https://github.com/SamRichardsDisney> , even though it is passing appveyor tests, it would be great to have to try a run with that branch before it gets merged.

**Closed** 2017-04-19 21:13 UTC

**Comment by justinfx** [comment] 2017-04-19 21:18
Tagged as v1.4.0
Lets see how it goes. Thanks!

**Comment by SamRichardsDisney** [comment] 2017-04-19 21:34
Thanks again!

Sam.
