### ISSUE TITLE
handling of stereo formatting

### ISSUE THREAD

**Issue by nzanepro** [sqlboy/fileseq#50] opened 2017-08-17 19:46 UTC
long time user, first time caller!

Is there any plan on handling stereo or view based formatting? nuke uses %v or %V and maybe there are ways I don't know about? not sure if this got standardized along the way.

fsd = fileseq.findSequenceOnDisk(self._filename)
  File "fileseq/filesequence.py", line 493, in findSequenceOnDisk
    raise FileSeqException(msg.format(pattern))
fileseq.exceptions.FileSeqException: no sequence found on disk matching comp_v01-%v.0001-0464#.jpg

**Comment by justinfx** [comment] 2017-08-17 21:26
It feels a little bit out of scope for fileseq to have this kind of logic. What does "%v" mean in the generic sense? What does it expand to? And what would you expect to see as a result when using it in terms of `findSequenceOnDisk()`?

**Comment by yawpitch** [comment] 2017-08-17 22:12
To provide a bit of context, this is a convention the Foundry introduced years ago in Nuke, and I believe Hiero (now part of Nuke Studio) and possibly some of their other programs support it as well.

For fileseq the problem is it's not really something that can be truly generic, as it depends on knowledge of the "views" (stereo eyes) in use.

For example, if you've got a Nuke scene with "left" and "right" views -- the default for a stereo setup -- then %v in the file path will be expanded to "l" for the left eye and "r" for the right eye. If the %V (note capital) token is used instead, then it expands to "left" and "right" respectively.

If however your Nuke scene is set up with custom view names (for whatever reason you've decided on "up", "down" and "strawberry") then they'd expand to the first letter (%v) or full name (%V) of each, which is why this is impossible to generalize without knowledge of the view names in use. It's also why it's difficult to merge sequences in the same directory which differ only on view (ie combine /abc_l.#.jpg and /abc_l.#.jpg into /abc_%v.#.jpg) without again knowing something about the context of what views are in use globally.

This syntax fell out of favor at a lot of facilities once it became possible to have both eyes in a single EXR 2.0 file, but it's still useful for jpg sequences and other formats that don't have that capability.

M

**Comment by justinfx** [comment] 2017-08-17 22:18
Right. These days I tend to see them expressed as subimages or channels in an exr as opposed to file naming conventions for multiple sequences. It seems like to support this in fileseq, one would need to be able to set the definition of the views somewhere. Maybe this is really just about wildcard support? i.e. what if you could do this:

```
findSequencesOnDisk("/path/to/stereo/image_{left,right}.#.jpg")
```

It should be easy for the application to format its sequence strings from the knowledge it has about the views.

**Comment by yawpitch** [comment] 2017-08-17 22:46
That would work, and would encapsulate the problem nicely.

A more complex alternative: at another place I worked at, where this was more common, we did something like the Decimal library, where there was a Context class -- I can't remember the exact name -- and you'd do something like:

with Context("left", "right"):
findSequencesOnDisk("/abc_%v.#.exr")

And we had a simplified one that picked up facility defaults and project settings from the DB:

with Stereo():
[...]

That had the added advantage of letting us set default padding and delim characters for the version number, frame padding, preferred representation (ie #### or %04s), etc, all of which would change show to show.

It is, however, a much larger addition.

M

**Comment by nzanepro** [comment] 2017-08-18 02:26
I like findSequencesOnDisk("/path/to/stereo/image_{left,right}.#.jpg") because then it can be arbitrary. nuke has a bunch of other "views" that they've added since stereo, specifically for multi camera 360 VR, since you can have an arbitrary number of cameras in a rig. I would love to request this feature. thanks!

**Comment by justinfx** [comment] 2017-08-18 02:49
Sounds like a reasonable feature. Will try and find time to look at that, unless someone beats me to a merge request ;-)

**Comment by justinfx** [comment] 2017-08-20 09:38
I had a play working out some support for this [here](https://github.com/sqlboy/fileseq/blob/34a0208ba2953d646d503eec5d43b658227e289e/src/fileseq/filesequence.py#L431).

Usage examples look like this:
```
findSequencesOnDisk('/path/to/files')
findSequencesOnDisk('/path/to/files/image_stereo_{left,right}.#.jpg')
findSequencesOnDisk('/path/to/files/imag?_*_{left,right}.@@@.jpg', strictPadding=True)
```

If the input path is not an existing directory, it will get treated as a path where the basename supports a pattern. This pattern will be applied to filter the resulting files. Although for all the work required to add this filtering, I feel like it is really similar to adding another line after a user calls `findSequencesOnDisk()`, to filter the sequences down by their basename. But maybe if the directory contains a ton of files, this would save some time in converting the undesired files to sequences. Do people usually populate single directories with tons of different image sequences? I feel it isn't as common to do this, so I hope this feature is really worth the extra work?

Have a play and let me know what you think. 
Branch: [50_findSequencesOnDisk_wildcard](https://github.com/sqlboy/fileseq/blob/50_findSequencesOnDisk_wildcard/src/fileseq/filesequence.py)

**Comment by nzanepro** [comment] 2017-08-23 23:35
on location, apologies for the delay.

i tried it a couple of times, 
findSequencesOnDisk('/path/to/files/image_stereo_left.#.jpg') works
but 
findSequencesOnDisk('/path/to/files/image_stereo_{left,right}.#.jpg') didn't.
nor 
findSequencesOnDisk('/path/to/files/image_stereo_{left}.#.jpg') 

 File "<stdin>", line 1, in <module>
  File ".....filesequence.py", line 578, in findSequenceOnDisk
    raise FileSeqException(msg.format(pattern))
fileseq.exceptions.FileSeqException: no sequence found on disk matching ....

thinking about it more, i think i would still want them as separate sequences. i'm not going to make a quicktime of all the left and right into one long movie, i'd still need them as separate sequences and therefore separate objects right? how would you suggest "to filter the sequences down by their base name"?

**Comment by justinfx** [comment] 2017-08-24 05:47
Are you sure you tested the "50_findSequencesOnDisk_wildcard" branch? There are tests exercising those left/right wildcards. 

No matter what, they would always be individual sequences. My work was only to allow you to more specifically filter down a single directory that apparently has unbounded numbers of file sequences in them, and you wanted just a left/right result (2 sequences returned).  So that being said, I was wondering if it is just pretty close to you doing this:

```
seqs =  findSequencesOnDisk('/path/to/files')

rx = re.compile(r'^image_stereo_(left|right).\d+.jpg$')
seqs = [s for s in seqs if rx.search(s.basename())]
```

**Comment by justinfx** [comment] 2017-09-03 21:43
Sorry for the delay. This has been merged to master.

**Closed by justinfx** 2017-09-03 21:43 UTC
Labels: enhancement
